name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build the book
        run: |
          pwd
          ls -la
          jupyter --version
          jupyter nbconvert --version
          jupyter nbconvert --to html prueba1.ipynb
          ls -la
          mv prueba1.html index.html
          ls -la
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: false
          force_orphan: true
      - name: Check deployment
        run: |
          git checkout gh-pages
          ls -la
